version: '3.8'

services:
  tomcat:
    image: tomcat:10.1
    container_name: laundry_tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./your-webapp-directory:/usr/local/tomcat/webapps
    environment:
      CATALINA_HOME: /usr/local/tomcat
      JAVA_OPTS: "-Djava.security.egd=file:/dev/./urandom"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laundry_mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_userroot
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laundry_phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - "8081:80"
